Attribute VB_Name = "Module1"
Sub countTickerSymbols()
    
    'Create a container to hold the number of records'
    'Avoid overflow by using LONG integer types'
    Dim recordQuantity2018, 
        recordQuantity2019, 
        recordQuantity2020 As Long

    'Manually verified record counts in worksheets'
    'Why are there different amounts of records?'
    'Are these records directly comparable?'
    recordQuantity2018 = 753000
    recordQuantity2019 = 756000
    recordQuantity2020 = 759000
    
    'This will pick up trading symbol "AAB"
    tradingSymbol = Range("A2").Value

    'Create for loop to count number of symbols
    'outer loop for each trading symbol
        'inner loop for each individual trading symbol of a set
        'end inner loop
    'end outer loop

    'Forloop to traverse the 2018 worksheet
    For i = 1 To recordQuantity2018 + 1
        If (Cells(i, 1).Value = tradingSymbol) Then

            quantityOfIndividualSymbols += 1
        End If
    Next iterator
    
    MsgBox (quantityOfIndividualSymbols)
    Range("I2").Value = tradingSymbol
    Range("J2").Value = quantityOfIndividualSymbols

'    - WHILE-LOOP
    While Boolean
        
    
'    - **Will only increment counter after a full inner traversal**
'    - *Note:* **This would require unsorted datasets to be sorted.**
'    - FOR-LOOP: 
'        - **This loop will reset it's counter each time it fully    traverses a single trading symbol, such as AAB, AAF, and so on.**
'        - 
'        - innerCounter = innerCounter + 1
'    - END INNER LOOP
'- END OUTER LOOP
End While 'Decided to use a while loop instead 

End Sub

'Part of the code for the helper function "dateFormatter" was generated by GPT-4'
'It has been partially edited by hand to reflect the context of which sheet it is reading/writing'
'Some comments have been added by hand for clarity to show what the code does.'
Sub dateFormatter()
    Dim dateString As String
    Dim year As String
    Dim month As String
    Dim day As String
    Dim formattedDate As Date

    dateString = 

    ' # Extract the year, month, and day from the date string
    
    ' Takes 4 characters starting from left-to-right of the dateString
    year = Left(dateString, 4)

    ' Takes 4 characters starting from the end of the range, to the start of the range
    month = Mid(dateString, 5, 2)

    ' Go two characters from right-to-left and store it in "day"
    day = Right(dateString, 2)

    ' Convert the extracted year, month, and day into a regular date format
    formattedDate = DateSerial(year, month, day)

End Sub
